// Languages and UI strings. {name} placeholders are filled by t();
// text between {hl} and {/hl} is highlighted with the brand gradient.
window.ZM_LANGUAGES = [
  { code: "ru", label: "Рус", name: "Русский" },
  { code: "uk", label: "Укр", name: "Українська" },
  { code: "be", label: "Бел", name: "Беларуская" },
  { code: "en", label: "Eng", name: "English" },
];
window.ZM_DEFAULT_LANG = "ru";

window.ZM_STRINGS = {
  title: {
    ru: "ZavtraMarket — Что будет завтра?",
    uk: "ZavtraMarket — Що буде завтра?",
    be: "ZavtraMarket — Што будзе заўтра?",
    en: "ZavtraMarket — What happens tomorrow?",
  },
  navMarkets: { ru: "Рынки", uk: "Ринки", be: "Рынкі", en: "Markets" },
  navPortfolio: { ru: "Портфель", uk: "Портфель", be: "Партфель", en: "Portfolio" },
  langSwitcher: { ru: "Язык", uk: "Мова", be: "Мова", en: "Language" },
  demoBanner: {
    ru: "Демо-режим: все рынки вымышлены, баланс виртуальный. Настоящие деньги не используются.",
    uk: "Демо-режим: усі ринки вигадані, баланс віртуальний. Справжні гроші не використовуються.",
    be: "Дэма-рэжым: усе рынкі выдуманыя, баланс віртуальны. Сапраўдныя грошы не выкарыстоўваюцца.",
    en: "Demo mode: every market is fictional and your balance is virtual. No real money is used.",
  },
  balance: { ru: "Баланс", uk: "Баланс", be: "Баланс", en: "Balance" },
  watchlist: { ru: "Избранное", uk: "Обране", be: "Абранае", en: "Watchlist" },
  sortLabel: { ru: "Сортировка", uk: "Сортування", be: "Сартаванне", en: "Sort" },
  sortVolume: { ru: "По объёму", uk: "За обсягом", be: "Па аб'ёме", en: "Volume" },
  sortClosing: { ru: "Скоро закроются", uk: "Скоро закриються", be: "Хутка закрыюцца", en: "Closing soon" },
  sortNew: { ru: "Новые", uk: "Нові", be: "Новыя", en: "Newest" },
  sortMovers: { ru: "Движение за 24 ч", uk: "Рух за 24 год", be: "Рух за 24 г", en: "24h movers" },
  noResults: { ru: "Ничего не найдено.", uk: "Нічого не знайдено.", be: "Нічога не знойдзена.", en: "No markets found." },
  emptyWatchlist: {
    ru: "Нажмите ☆ на карточке рынка, чтобы добавить его в избранное.",
    uk: "Натисніть ☆ на картці ринку, щоб додати його до обраного.",
    be: "Націсніце ☆ на картцы рынку, каб дадаць яго ў абранае.",
    en: "Tap ☆ on a market card to add it to your watchlist.",
  },
  volume: { ru: "{v} объём", uk: "{v} обсяг", be: "{v} аб'ём", en: "{v} vol" },
  closes: { ru: "до {d}", uk: "до {d}", be: "да {d}", en: "ends {d}" },
  chance: { ru: "шанс", uk: "шанс", be: "шанец", en: "chance" },
  yes: { ru: "Да", uk: "Так", be: "Так", en: "Yes" },
  no: { ru: "Нет", uk: "Ні", be: "Не", en: "No" },
  moreOutcomes: { ru: "+ ещё {n}", uk: "+ ще {n}", be: "+ яшчэ {n}", en: "+ {n} more" },
  watchAdd: { ru: "В избранное", uk: "До обраного", be: "У абранае", en: "Add to watchlist" },
  watchRemove: { ru: "Убрать из избранного", uk: "Прибрати з обраного", be: "Прыбраць з абранага", en: "Remove from watchlist" },
  backToMarkets: { ru: "← Все рынки", uk: "← Усі ринки", be: "← Усе рынкі", en: "← All markets" },
  notFound: { ru: "Рынок не найден.", uk: "Ринок не знайдено.", be: "Рынак не знойдзены.", en: "Market not found." },
  outcome: { ru: "Исход", uk: "Результат", be: "Вынік", en: "Outcome" },
  chanceCol: { ru: "Шанс", uk: "Шанс", be: "Шанец", en: "Chance" },
  range1d: { ru: "1Д", uk: "1Д", be: "1Д", en: "1D" },
  range1w: { ru: "1Н", uk: "1Т", be: "1Т", en: "1W" },
  range1m: { ru: "1М", uk: "1М", be: "1М", en: "1M" },
  rangeAll: { ru: "Всё", uk: "Усе", be: "Усё", en: "All" },
  orderBook: { ru: "Стакан заявок", uk: "Книга заявок", be: "Кніга заявак", en: "Order book" },
  bookPrice: { ru: "Цена", uk: "Ціна", be: "Цана", en: "Price" },
  bookQty: { ru: "Контракты", uk: "Контракти", be: "Кантракты", en: "Contracts" },
  bookTotal: { ru: "Сумма", uk: "Сума", be: "Сума", en: "Total" },
  asks: { ru: "Продажа", uk: "Продаж", be: "Продаж", en: "Asks" },
  bids: { ru: "Покупка", uk: "Купівля", be: "Купля", en: "Bids" },
  spread: { ru: "Спред {s}¢", uk: "Спред {s}¢", be: "Спрэд {s}¢", en: "Spread {s}¢" },
  rules: { ru: "Правила", uk: "Правила", be: "Правілы", en: "Rules" },
  rulesBinary: {
    ru: "Рынок разрешится «Да», если событие из заголовка наступит до {d}. Источник итога: {src}. Каждый контракт «Да» выплачивает $1, если событие наступит, каждый контракт «Нет» — $1, если нет.",
    uk: "Ринок розв'яжеться «Так», якщо подія із заголовка настане до {d}. Джерело результату: {src}. Кожен контракт «Так» виплачує $1, якщо подія настане, кожен контракт «Ні» — $1, якщо ні.",
    be: "Рынак вырашыцца «Так», калі падзея з загалоўка адбудзецца да {d}. Крыніца выніку: {src}. Кожны кантракт «Так» выплачвае $1, калі падзея адбудзецца, кожны кантракт «Не» — $1, калі не.",
    en: "This market resolves Yes if the event in the title happens by {d}. Resolution source: {src}. Each Yes contract pays $1 if it happens; each No contract pays $1 if it doesn't.",
  },
  rulesMulti: {
    ru: "Для каждого исхода есть отдельный рынок. Исход, подтверждённый источником ({src}) на {d}, разрешится «Да», все остальные — «Нет». Каждый выигравший контракт выплачивает $1.",
    uk: "Для кожного результату є окремий ринок. Результат, підтверджений джерелом ({src}) на {d}, розв'яжеться «Так», усі інші — «Ні». Кожен виграшний контракт виплачує $1.",
    be: "Для кожнага выніку ёсць асобны рынак. Вынік, пацверджаны крыніцай ({src}) на {d}, вырашыцца «Так», усе астатнія — «Не». Кожны выйгрышны кантракт выплачвае $1.",
    en: "Each outcome is its own market. The outcome confirmed by {src} as of {d} resolves Yes; every other outcome resolves No. Each winning contract pays $1.",
  },
  timeline: { ru: "Сроки", uk: "Терміни", be: "Тэрміны", en: "Timeline" },
  opened: { ru: "Открыт", uk: "Відкрито", be: "Адкрыты", en: "Opened" },
  closing: { ru: "Закрытие торгов", uk: "Закриття торгів", be: "Закрыццё таргоў", en: "Trading closes" },
  payoutWhen: { ru: "Выплата", uk: "Виплата", be: "Выплата", en: "Payout" },
  payoutWhenText: { ru: "вскоре после итога", uk: "невдовзі після результату", be: "неўзабаве пасля выніку", en: "shortly after the outcome" },
  related: { ru: "Похожие рынки", uk: "Схожі ринки", be: "Падобныя рынкі", en: "Related markets" },
  buy: { ru: "Купить", uk: "Купити", be: "Купіць", en: "Buy" },
  sell: { ru: "Продать", uk: "Продати", be: "Прадаць", en: "Sell" },
  orderMarket: { ru: "Рыночный", uk: "Ринковий", be: "Рынкавы", en: "Market" },
  orderLimit: { ru: "Лимитный", uk: "Лімітний", be: "Лімітны", en: "Limit" },
  amount: { ru: "Сумма, $", uk: "Сума, $", be: "Сума, $", en: "Amount, $" },
  limitPrice: { ru: "Цена, ¢", uk: "Ціна, ¢", be: "Цана, ¢", en: "Limit price, ¢" },
  contracts: { ru: "Контракты", uk: "Контракти", be: "Кантракты", en: "Contracts" },
  avgPrice: { ru: "Средняя цена", uk: "Середня ціна", be: "Сярэдняя цана", en: "Avg. price" },
  cost: { ru: "Стоимость", uk: "Вартість", be: "Кошт", en: "Cost" },
  toWin: { ru: "Выплата при выигрыше", uk: "Виплата в разі виграшу", be: "Выплата пры выйгрышы", en: "Payout if right" },
  proceeds: { ru: "Вы получите", uk: "Ви отримаєте", be: "Вы атрымаеце", en: "You receive" },
  submitBuy: { ru: "Купить «{side}»", uk: "Купити «{side}»", be: "Купіць «{side}»", en: "Buy {side}" },
  submitSell: { ru: "Продать «{side}»", uk: "Продати «{side}»", be: "Прадаць «{side}»", en: "Sell {side}" },
  placeLimit: { ru: "Выставить заявку", uk: "Виставити заявку", be: "Выставіць заяўку", en: "Place order" },
  insufficient: { ru: "Недостаточно средств", uk: "Недостатньо коштів", be: "Недастаткова сродкаў", en: "Insufficient balance" },
  enterAmount: { ru: "Введите сумму", uk: "Введіть суму", be: "Увядзіце суму", en: "Enter an amount" },
  noPosition: {
    ru: "У вас нет контрактов «{side}» на этот исход.",
    uk: "У вас немає контрактів «{side}» на цей результат.",
    be: "У вас няма кантрактаў «{side}» на гэты вынік.",
    en: "You don't hold any {side} contracts on this outcome.",
  },
  youHold: { ru: "У вас {n} контр. «{side}»", uk: "У вас {n} контр. «{side}»", be: "У вас {n} кантр. «{side}»", en: "You hold {n} {side} contracts" },
  sellAll: { ru: "Все", uk: "Усі", be: "Усе", en: "Max" },
  limitHint: {
    ru: "Заявка исполнится, когда цена «{side}» опустится до {p}¢.",
    uk: "Заявка виконається, коли ціна «{side}» знизиться до {p}¢.",
    be: "Заяўка выканаецца, калі цана «{side}» знізіцца да {p}¢.",
    en: "Fills when the {side} price drops to {p}¢.",
  },
  toastBought: {
    ru: "Куплено {n} контр. «{side}» по {p}¢",
    uk: "Куплено {n} контр. «{side}» по {p}¢",
    be: "Куплена {n} кантр. «{side}» па {p}¢",
    en: "Bought {n} {side} at {p}¢",
  },
  toastSold: {
    ru: "Продано {n} контр. «{side}» по {p}¢",
    uk: "Продано {n} контр. «{side}» по {p}¢",
    be: "Прададзена {n} кантр. «{side}» па {p}¢",
    en: "Sold {n} {side} at {p}¢",
  },
  toastPlaced: {
    ru: "Заявка выставлена: {n} контр. «{side}» по {p}¢",
    uk: "Заявку виставлено: {n} контр. «{side}» по {p}¢",
    be: "Заяўка выстаўлена: {n} кантр. «{side}» па {p}¢",
    en: "Order placed: {n} {side} at {p}¢",
  },
  toastFilled: {
    ru: "Заявка исполнена: {n} контр. «{side}» по {p}¢",
    uk: "Заявку виконано: {n} контр. «{side}» по {p}¢",
    be: "Заяўка выканана: {n} кантр. «{side}» па {p}¢",
    en: "Order filled: {n} {side} at {p}¢",
  },
  toastCanceled: { ru: "Заявка отменена", uk: "Заявку скасовано", be: "Заяўка адменена", en: "Order canceled" },
  cash: { ru: "Свободные средства", uk: "Вільні кошти", be: "Вольныя сродкі", en: "Cash" },
  positionsValue: { ru: "Стоимость позиций", uk: "Вартість позицій", be: "Кошт пазіцый", en: "Positions value" },
  totalPnl: { ru: "Прибыль / убыток", uk: "Прибуток / збиток", be: "Прыбытак / страта", en: "Profit / loss" },
  positions: { ru: "Позиции", uk: "Позиції", be: "Пазіцыі", en: "Positions" },
  openOrders: { ru: "Заявки", uk: "Заявки", be: "Заяўкі", en: "Open orders" },
  history: { ru: "История", uk: "Історія", be: "Гісторыя", en: "History" },
  noPositions: {
    ru: "Позиций пока нет. Выберите рынок и купите «Да» или «Нет».",
    uk: "Позицій поки немає. Оберіть ринок і купіть «Так» або «Ні».",
    be: "Пазіцый пакуль няма. Абярыце рынак і купіце «Так» або «Не».",
    en: "No positions yet. Pick a market and buy Yes or No.",
  },
  noOrders: { ru: "Нет открытых заявок.", uk: "Немає відкритих заявок.", be: "Няма адкрытых заявак.", en: "No open orders." },
  noHistory: { ru: "Сделок пока не было.", uk: "Угод поки не було.", be: "Здзелак пакуль не было.", en: "No trades yet." },
  colMarket: { ru: "Рынок", uk: "Ринок", be: "Рынак", en: "Market" },
  colSide: { ru: "Сторона", uk: "Сторона", be: "Бок", en: "Side" },
  colAvg: { ru: "Ср. цена", uk: "Сер. ціна", be: "Ср. цана", en: "Avg." },
  colNow: { ru: "Сейчас", uk: "Зараз", be: "Цяпер", en: "Now" },
  colValue: { ru: "Стоимость", uk: "Вартість", be: "Кошт", en: "Value" },
  colPnl: { ru: "П/У", uk: "П/З", be: "П/С", en: "P/L" },
  colPrice: { ru: "Цена", uk: "Ціна", be: "Цана", en: "Price" },
  colTime: { ru: "Время", uk: "Час", be: "Час", en: "Time" },
  colAction: { ru: "Действие", uk: "Дія", be: "Дзеянне", en: "Action" },
  cancel: { ru: "Отменить", uk: "Скасувати", be: "Адмяніць", en: "Cancel" },
  actionBuy: { ru: "Покупка", uk: "Купівля", be: "Купля", en: "Buy" },
  actionSell: { ru: "Продажа", uk: "Продаж", be: "Продаж", en: "Sell" },
  resetDemo: { ru: "Сбросить демо", uk: "Скинути демо", be: "Скінуць дэма", en: "Reset demo" },
  resetConfirm: {
    ru: "Сбросить баланс до $1 000 и удалить все позиции, заявки и историю?",
    uk: "Скинути баланс до $1 000 і видалити всі позиції, заявки та історію?",
    be: "Скінуць баланс да $1 000 і выдаліць усе пазіцыі, заяўкі і гісторыю?",
    en: "Reset your balance to $1,000 and clear all positions, orders and history?",
  },
  footer: {
    ru: "ZavtraMarket находится в разработке. Это демо: рынки, цены и объёмы вымышлены, торговля ведётся виртуальными деньгами.",
    uk: "ZavtraMarket перебуває в розробці. Це демо: ринки, ціни й обсяги вигадані, торгівля ведеться віртуальними грошима.",
    be: "ZavtraMarket знаходзіцца ў распрацоўцы. Гэта дэма: рынкі, цэны і аб'ёмы выдуманыя, гандаль вядзецца віртуальнымі грашыма.",
    en: "ZavtraMarket is in development. This is a demo: markets, prices and volumes are made up, and trading uses virtual money.",
  },
  joinWaitlist: { ru: "Записаться в лист ожидания", uk: "Записатися до списку очікування", be: "Запісацца ў спіс чакання", en: "Join the waitlist" },
  slogan: {
    ru: "Что будет {hl}завтра{/hl}?",
    uk: "Що буде {hl}завтра{/hl}?",
    be: "Што будзе {hl}заўтра{/hl}?",
    en: "What happens {hl}tomorrow{/hl}?",
  },
  subhead: {
    ru: "ZavtraMarket — рынок прогнозов: выборы, футбол, курсы валют, культура. Скажи, во что веришь. Подтверди ставкой. Получи выплату, если оказался прав.",
    uk: "ZavtraMarket — ринок прогнозів: вибори, футбол, курси валют, культура. Скажи, у що віриш. Підтвердь ставкою. Отримай виплату, якщо мав рацію.",
    be: "ZavtraMarket — рынак прагнозаў: выбары, футбол, курсы валют, культура. Скажы, у што верыш. Пацвердзі стаўкай. Атрымай выплату, калі меў рацыю.",
    en: "ZavtraMarket is a prediction market for elections, football, currencies and culture. Say what you believe. Back it. Get paid when you're right.",
  },
  emailLabel: { ru: "Электронная почта", uk: "Електронна пошта", be: "Электронная пошта", en: "Email address" },
  formSuccess: {
    ru: "Вы в списке. До скорой встречи.",
    uk: "Ви в списку. До зустрічі.",
    be: "Вы ў спісе. Да сустрэчы.",
    en: "You're on the list. See you soon.",
  },
  formInvalid: {
    ru: "Введите корректный адрес почты.",
    uk: "Введіть коректну адресу пошти.",
    be: "Увядзіце карэктны адрас пошты.",
    en: "Enter a valid email address.",
  },
  ctaTitle: { ru: "Узнай первым о запуске.", uk: "Дізнайся першим про запуск.", be: "Даведайся першым пра запуск.", en: "Be first when we open." },
  ctaText: {
    ru: "Никакого спама. Одно письмо в день запуска ZavtraMarket.",
    uk: "Жодного спаму. Один лист у день запуску ZavtraMarket.",
    be: "Ніякага спаму. Адзін ліст у дзень запуску ZavtraMarket.",
    en: "No spam. One email when ZavtraMarket launches.",
  },
  howTitle: { ru: "Как это работает", uk: "Як це працює", be: "Як гэта працуе", en: "How it works" },
  step1Title: { ru: "Выбери вопрос", uk: "Обери питання", be: "Абяры пытанне", en: "Pick a question" },
  step1Text: {
    ru: "Реальные события, важные для региона: политика, спорт, экономика, культура.",
    uk: "Реальні події, важливі для регіону: політика, спорт, економіка, культура.",
    be: "Рэальныя падзеі, важныя для рэгіёна: палітыка, спорт, эканоміка, культура.",
    en: "Real events that matter to our region — politics, sport, economy, culture.",
  },
  step2Title: { ru: "Подтверди прогноз", uk: "Підтвердь прогноз", be: "Пацвердзі прагноз", en: "Back your prediction" },
  step2Text: {
    ru: "Зафиксируй свою позицию и торгуй по мере изменения шансов.",
    uk: "Зафіксуй свою позицію й торгуй у міру зміни шансів.",
    be: "Зафіксуй сваю пазіцыю і гандлюй па меры змены шанцаў.",
    en: "Put your view on record and trade shares as odds shift.",
  },
  step3Title: {
    ru: "Получи выплату, если прав",
    uk: "Отримай виплату, якщо маєш рацію",
    be: "Атрымай выплату, калі маеш рацыю",
    en: "Get paid when you're right",
  },
  step3Text: {
    ru: "Рынки закрываются по проверенным итогам. Победители выводят средства мгновенно.",
    uk: "Ринки закриваються за перевіреними підсумками. Переможці виводять кошти миттєво.",
    be: "Рынкі закрываюцца па правераных выніках. Пераможцы выводзяць сродкі імгненна.",
    en: "Markets settle on verified outcomes. Winners cash out instantly.",
  },
  whyTitle: { ru: "Создано для наших рынков", uk: "Створено для наших ринків", be: "Створана для нашых рынкаў", en: "Built for our markets" },
  whyLead: {
    ru: "Глобальные рынки прогнозов обходят стороной то, что действительно важно здесь. Мы — нет.",
    uk: "Глобальні ринки прогнозів оминають те, що справді важливо тут. Ми — ні.",
    be: "Глабальныя рынкі прагнозаў абыходзяць бокам тое, што сапраўды важна тут. Мы — не.",
    en: "Global prediction markets skip the questions that actually matter here. We don't.",
  },
  regionTitle: { ru: "Региональный охват", uk: "Регіональне охоплення", be: "Рэгіянальны ахоп", en: "Regional coverage" },
  regionText: {
    ru: "Рынки на события, лиги и выборы, которые заполняют наши ленты, а не второстепенная категория где-то внизу списка.",
    uk: "Ринки на події, ліги й вибори, якими заповнені наші стрічки, а не другорядна категорія десь унизу списку.",
    be: "Рынкі на падзеі, лігі і выбары, якімі запоўнены нашы стужкі, а не другарадная катэгорыя дзесьці ўнізе спіса.",
    en: "Markets on the events, leagues and elections that dominate our feeds — not an afterthought category.",
  },
  languageTitle: { ru: "Говорит на вашем языке", uk: "Говорить вашою мовою", be: "Размаўляе на вашай мове", en: "Speaks your language" },
  languageText: {
    ru: "Русский, украинский, белорусский и английский — с первого дня.",
    uk: "Російська, українська, білоруська та англійська — з першого дня.",
    be: "Руская, украінская, беларуская і англійская — з першага дня.",
    en: "Russian, Ukrainian, Belarusian and English from day one.",
  },
  settleTitle: { ru: "Прозрачные расчёты", uk: "Прозорі розрахунки", be: "Празрыстыя разлікі", en: "Transparent settlement" },
  settleText: {
    ru: "Понятные источники для каждого решения — итоги никогда не определяются на глаз.",
    uk: "Зрозумілі джерела для кожного рішення — підсумки ніколи не визначаються на око.",
    be: "Зразумелыя крыніцы для кожнага рашэння — вынікі ніколі не вызначаюцца на вока.",
    en: "Clear sourcing on every resolution, so outcomes are never a judgment call.",
  },
  footerTagline: {
    ru: "zavtramarket.com — рынки прогнозов, начиная с завтра.",
    uk: "zavtramarket.com — ринки прогнозів, починаючи із завтра.",
    be: "zavtramarket.com — рынкі прагнозаў, пачынаючы з заўтра.",
    en: "zavtramarket.com — prediction markets, tomorrow.",
  },
  navLive: { ru: "Live", uk: "Live", be: "Live", en: "Live" },
  searchAnything: { ru: "Торгуйте на чём угодно", uk: "Торгуйте будь-чим", be: "Гандлюйце чым заўгодна", en: "Trade on anything" },
  signUp: { ru: "Записаться", uk: "Записатися", be: "Запісацца", en: "Join waitlist" },
  close: { ru: "Закрыть", uk: "Закрити", be: "Закрыць", en: "Close" },
  pager: { ru: "{i} из {n}", uk: "{i} з {n}", be: "{i} з {n}", en: "{i} of {n}" },
  prevMarket: { ru: "Предыдущий рынок", uk: "Попередній ринок", be: "Папярэдні рынак", en: "Previous market" },
  nextMarket: { ru: "Следующий рынок", uk: "Наступний ринок", be: "Наступны рынак", en: "Next market" },
  colPayout: { ru: "Выплата", uk: "Виплата", be: "Выплата", en: "Pays out" },
  allMarkets: { ru: "Все рынки", uk: "Усі ринки", be: "Усе рынкі", en: "All markets" },
  searchResults: { ru: "Результаты поиска", uk: "Результати пошуку", be: "Вынікі пошуку", en: "Search results" },
  info1Title: { ru: "Как устроены рынки", uk: "Як влаштовані ринки", be: "Як уладкаваныя рынкі", en: "How markets work" },
  info1Text: {
    ru: "Купите «Да» или «Нет» — верный прогноз приносит $1",
    uk: "Купіть «Так» або «Ні» — правильний прогноз приносить $1",
    be: "Купіце «Так» або «Не» — правільны прагноз прыносіць $1",
    en: "Buy Yes or No — a correct call pays $1",
  },
  info2Text: {
    ru: "У каждого рынка — понятный источник итога",
    uk: "Кожен ринок має зрозуміле джерело результату",
    be: "У кожнага рынку — зразумелая крыніца выніку",
    en: "Every market names its resolution source",
  },
  info3Title: { ru: "Ответственная торговля", uk: "Відповідальна торгівля", be: "Адказны гандаль", en: "Responsible trading" },
  info3Text: {
    ru: "Это демо: виртуальный баланс, никакого риска",
    uk: "Це демо: віртуальний баланс, жодного ризику",
    be: "Гэта дэма: віртуальны баланс, ніякай рызыкі",
    en: "This is a demo: virtual balance, zero risk",
  },
  liveLead: {
    ru: "Рынки, где цена изменилась за последнюю минуту.",
    uk: "Ринки, де ціна змінилася за останню хвилину.",
    be: "Рынкі, дзе цана змянілася за апошнюю хвіліну.",
    en: "Markets whose price moved in the last minute.",
  },
  liveEmpty: {
    ru: "Пока тихо — цены обновляются каждые несколько секунд.",
    uk: "Поки тихо — ціни оновлюються кожні кілька секунд.",
    be: "Пакуль ціха — цэны абнаўляюцца кожныя некалькі секунд.",
    en: "Quiet for now — prices update every few seconds.",
  },
};
