// UI strings for the markets demo. {name} placeholders are filled by t().
window.ZM_STRINGS = {
  title: { ru: "Рынки · ZavtraMarket", uk: "Ринки · ZavtraMarket", be: "Рынкі · ZavtraMarket", en: "Markets · ZavtraMarket" },
  navMarkets: { ru: "Рынки", uk: "Ринки", be: "Рынкі", en: "Markets" },
  navPortfolio: { ru: "Портфель", uk: "Портфель", be: "Партфель", en: "Portfolio" },
  langSwitcher: { ru: "Язык", uk: "Мова", be: "Мова", en: "Language" },
  search: { ru: "Поиск рынков", uk: "Пошук ринків", be: "Пошук рынкаў", en: "Search markets" },
  demoBanner: {
    ru: "Демо-режим: все рынки вымышлены, баланс виртуальный. Настоящие деньги не используются.",
    uk: "Демо-режим: усі ринки вигадані, баланс віртуальний. Справжні гроші не використовуються.",
    be: "Дэма-рэжым: усе рынкі выдуманыя, баланс віртуальны. Сапраўдныя грошы не выкарыстоўваюцца.",
    en: "Demo mode: every market is fictional and your balance is virtual. No real money is used.",
  },
  balance: { ru: "Баланс", uk: "Баланс", be: "Баланс", en: "Balance" },
  watchlist: { ru: "Избранное", uk: "Обране", be: "Абранае", en: "Watchlist" },
  sortLabel: { ru: "Сортировка", uk: "Сортування", be: "Сартаванне", en: "Sort" },
  sortVolume: { ru: "По объёму", uk: "За обсягом", be: "Па аб'ёме", en: "Volume" },
  sortClosing: { ru: "Скоро закроются", uk: "Скоро закриються", be: "Хутка закрыюцца", en: "Closing soon" },
  sortNew: { ru: "Новые", uk: "Нові", be: "Новыя", en: "Newest" },
  sortMovers: { ru: "Движение за 24 ч", uk: "Рух за 24 год", be: "Рух за 24 г", en: "24h movers" },
  noResults: { ru: "Ничего не найдено.", uk: "Нічого не знайдено.", be: "Нічога не знойдзена.", en: "No markets found." },
  emptyWatchlist: {
    ru: "Нажмите ☆ на карточке рынка, чтобы добавить его в избранное.",
    uk: "Натисніть ☆ на картці ринку, щоб додати його до обраного.",
    be: "Націсніце ☆ на картцы рынку, каб дадаць яго ў абранае.",
    en: "Tap ☆ on a market card to add it to your watchlist.",
  },
  volume: { ru: "{v} объём", uk: "{v} обсяг", be: "{v} аб'ём", en: "{v} vol" },
  closes: { ru: "до {d}", uk: "до {d}", be: "да {d}", en: "ends {d}" },
  chance: { ru: "шанс", uk: "шанс", be: "шанец", en: "chance" },
  yes: { ru: "Да", uk: "Так", be: "Так", en: "Yes" },
  no: { ru: "Нет", uk: "Ні", be: "Не", en: "No" },
  moreOutcomes: { ru: "+ ещё {n}", uk: "+ ще {n}", be: "+ яшчэ {n}", en: "+ {n} more" },
  watchAdd: { ru: "В избранное", uk: "До обраного", be: "У абранае", en: "Add to watchlist" },
  watchRemove: { ru: "Убрать из избранного", uk: "Прибрати з обраного", be: "Прыбраць з абранага", en: "Remove from watchlist" },
  backToMarkets: { ru: "← Все рынки", uk: "← Усі ринки", be: "← Усе рынкі", en: "← All markets" },
  notFound: { ru: "Рынок не найден.", uk: "Ринок не знайдено.", be: "Рынак не знойдзены.", en: "Market not found." },
  outcome: { ru: "Исход", uk: "Результат", be: "Вынік", en: "Outcome" },
  chanceCol: { ru: "Шанс", uk: "Шанс", be: "Шанец", en: "Chance" },
  range1d: { ru: "1Д", uk: "1Д", be: "1Д", en: "1D" },
  range1w: { ru: "1Н", uk: "1Т", be: "1Т", en: "1W" },
  range1m: { ru: "1М", uk: "1М", be: "1М", en: "1M" },
  rangeAll: { ru: "Всё", uk: "Усе", be: "Усё", en: "All" },
  orderBook: { ru: "Стакан заявок", uk: "Книга заявок", be: "Кніга заявак", en: "Order book" },
  bookPrice: { ru: "Цена", uk: "Ціна", be: "Цана", en: "Price" },
  bookQty: { ru: "Контракты", uk: "Контракти", be: "Кантракты", en: "Contracts" },
  bookTotal: { ru: "Сумма", uk: "Сума", be: "Сума", en: "Total" },
  asks: { ru: "Продажа", uk: "Продаж", be: "Продаж", en: "Asks" },
  bids: { ru: "Покупка", uk: "Купівля", be: "Купля", en: "Bids" },
  spread: { ru: "Спред {s}¢", uk: "Спред {s}¢", be: "Спрэд {s}¢", en: "Spread {s}¢" },
  rules: { ru: "Правила", uk: "Правила", be: "Правілы", en: "Rules" },
  rulesBinary: {
    ru: "Рынок разрешится «Да», если событие из заголовка наступит до {d}. Источник итога: {src}. Каждый контракт «Да» выплачивает $1, если событие наступит, каждый контракт «Нет» — $1, если нет.",
    uk: "Ринок розв'яжеться «Так», якщо подія із заголовка настане до {d}. Джерело результату: {src}. Кожен контракт «Так» виплачує $1, якщо подія настане, кожен контракт «Ні» — $1, якщо ні.",
    be: "Рынак вырашыцца «Так», калі падзея з загалоўка адбудзецца да {d}. Крыніца выніку: {src}. Кожны кантракт «Так» выплачвае $1, калі падзея адбудзецца, кожны кантракт «Не» — $1, калі не.",
    en: "This market resolves Yes if the event in the title happens by {d}. Resolution source: {src}. Each Yes contract pays $1 if it happens; each No contract pays $1 if it doesn't.",
  },
  rulesMulti: {
    ru: "Для каждого исхода есть отдельный рынок. Исход, подтверждённый источником ({src}) на {d}, разрешится «Да», все остальные — «Нет». Каждый выигравший контракт выплачивает $1.",
    uk: "Для кожного результату є окремий ринок. Результат, підтверджений джерелом ({src}) на {d}, розв'яжеться «Так», усі інші — «Ні». Кожен виграшний контракт виплачує $1.",
    be: "Для кожнага выніку ёсць асобны рынак. Вынік, пацверджаны крыніцай ({src}) на {d}, вырашыцца «Так», усе астатнія — «Не». Кожны выйгрышны кантракт выплачвае $1.",
    en: "Each outcome is its own market. The outcome confirmed by {src} as of {d} resolves Yes; every other outcome resolves No. Each winning contract pays $1.",
  },
  timeline: { ru: "Сроки", uk: "Терміни", be: "Тэрміны", en: "Timeline" },
  opened: { ru: "Открыт", uk: "Відкрито", be: "Адкрыты", en: "Opened" },
  closing: { ru: "Закрытие торгов", uk: "Закриття торгів", be: "Закрыццё таргоў", en: "Trading closes" },
  payoutWhen: { ru: "Выплата", uk: "Виплата", be: "Выплата", en: "Payout" },
  payoutWhenText: { ru: "вскоре после итога", uk: "невдовзі після результату", be: "неўзабаве пасля выніку", en: "shortly after the outcome" },
  related: { ru: "Похожие рынки", uk: "Схожі ринки", be: "Падобныя рынкі", en: "Related markets" },
  buy: { ru: "Купить", uk: "Купити", be: "Купіць", en: "Buy" },
  sell: { ru: "Продать", uk: "Продати", be: "Прадаць", en: "Sell" },
  orderMarket: { ru: "Рыночный", uk: "Ринковий", be: "Рынкавы", en: "Market" },
  orderLimit: { ru: "Лимитный", uk: "Лімітний", be: "Лімітны", en: "Limit" },
  amount: { ru: "Сумма, $", uk: "Сума, $", be: "Сума, $", en: "Amount, $" },
  limitPrice: { ru: "Цена, ¢", uk: "Ціна, ¢", be: "Цана, ¢", en: "Limit price, ¢" },
  contracts: { ru: "Контракты", uk: "Контракти", be: "Кантракты", en: "Contracts" },
  avgPrice: { ru: "Средняя цена", uk: "Середня ціна", be: "Сярэдняя цана", en: "Avg. price" },
  cost: { ru: "Стоимость", uk: "Вартість", be: "Кошт", en: "Cost" },
  toWin: { ru: "Выплата при выигрыше", uk: "Виплата в разі виграшу", be: "Выплата пры выйгрышы", en: "Payout if right" },
  proceeds: { ru: "Вы получите", uk: "Ви отримаєте", be: "Вы атрымаеце", en: "You receive" },
  submitBuy: { ru: "Купить «{side}»", uk: "Купити «{side}»", be: "Купіць «{side}»", en: "Buy {side}" },
  submitSell: { ru: "Продать «{side}»", uk: "Продати «{side}»", be: "Прадаць «{side}»", en: "Sell {side}" },
  placeLimit: { ru: "Выставить заявку", uk: "Виставити заявку", be: "Выставіць заяўку", en: "Place order" },
  insufficient: { ru: "Недостаточно средств", uk: "Недостатньо коштів", be: "Недастаткова сродкаў", en: "Insufficient balance" },
  enterAmount: { ru: "Введите сумму", uk: "Введіть суму", be: "Увядзіце суму", en: "Enter an amount" },
  noPosition: { ru: "У вас нет контрактов «{side}» на этот исход.", uk: "У вас немає контрактів «{side}» на цей результат.", be: "У вас няма кантрактаў «{side}» на гэты вынік.", en: "You don't hold any {side} contracts on this outcome." },
  youHold: { ru: "У вас {n} контр. «{side}»", uk: "У вас {n} контр. «{side}»", be: "У вас {n} кантр. «{side}»", en: "You hold {n} {side} contracts" },
  sellAll: { ru: "Все", uk: "Усі", be: "Усе", en: "Max" },
  limitHint: {
    ru: "Заявка исполнится, когда цена «{side}» опустится до {p}¢.",
    uk: "Заявка виконається, коли ціна «{side}» знизиться до {p}¢.",
    be: "Заяўка выканаецца, калі цана «{side}» знізіцца да {p}¢.",
    en: "Fills when the {side} price drops to {p}¢.",
  },
  toastBought: { ru: "Куплено {n} контр. «{side}» по {p}¢", uk: "Куплено {n} контр. «{side}» по {p}¢", be: "Куплена {n} кантр. «{side}» па {p}¢", en: "Bought {n} {side} at {p}¢" },
  toastSold: { ru: "Продано {n} контр. «{side}» по {p}¢", uk: "Продано {n} контр. «{side}» по {p}¢", be: "Прададзена {n} кантр. «{side}» па {p}¢", en: "Sold {n} {side} at {p}¢" },
  toastPlaced: { ru: "Заявка выставлена: {n} контр. «{side}» по {p}¢", uk: "Заявку виставлено: {n} контр. «{side}» по {p}¢", be: "Заяўка выстаўлена: {n} кантр. «{side}» па {p}¢", en: "Order placed: {n} {side} at {p}¢" },
  toastFilled: { ru: "Заявка исполнена: {n} контр. «{side}» по {p}¢", uk: "Заявку виконано: {n} контр. «{side}» по {p}¢", be: "Заяўка выканана: {n} кантр. «{side}» па {p}¢", en: "Order filled: {n} {side} at {p}¢" },
  toastCanceled: { ru: "Заявка отменена", uk: "Заявку скасовано", be: "Заяўка адменена", en: "Order canceled" },
  cash: { ru: "Свободные средства", uk: "Вільні кошти", be: "Вольныя сродкі", en: "Cash" },
  positionsValue: { ru: "Стоимость позиций", uk: "Вартість позицій", be: "Кошт пазіцый", en: "Positions value" },
  totalPnl: { ru: "Прибыль / убыток", uk: "Прибуток / збиток", be: "Прыбытак / страта", en: "Profit / loss" },
  positions: { ru: "Позиции", uk: "Позиції", be: "Пазіцыі", en: "Positions" },
  openOrders: { ru: "Заявки", uk: "Заявки", be: "Заяўкі", en: "Open orders" },
  history: { ru: "История", uk: "Історія", be: "Гісторыя", en: "History" },
  noPositions: { ru: "Позиций пока нет. Выберите рынок и купите «Да» или «Нет».", uk: "Позицій поки немає. Оберіть ринок і купіть «Так» або «Ні».", be: "Пазіцый пакуль няма. Абярыце рынак і купіце «Так» або «Не».", en: "No positions yet. Pick a market and buy Yes or No." },
  noOrders: { ru: "Нет открытых заявок.", uk: "Немає відкритих заявок.", be: "Няма адкрытых заявак.", en: "No open orders." },
  noHistory: { ru: "Сделок пока не было.", uk: "Угод поки не було.", be: "Здзелак пакуль не было.", en: "No trades yet." },
  colMarket: { ru: "Рынок", uk: "Ринок", be: "Рынак", en: "Market" },
  colSide: { ru: "Сторона", uk: "Сторона", be: "Бок", en: "Side" },
  colAvg: { ru: "Ср. цена", uk: "Сер. ціна", be: "Ср. цана", en: "Avg." },
  colNow: { ru: "Сейчас", uk: "Зараз", be: "Цяпер", en: "Now" },
  colValue: { ru: "Стоимость", uk: "Вартість", be: "Кошт", en: "Value" },
  colPnl: { ru: "П/У", uk: "П/З", be: "П/С", en: "P/L" },
  colPrice: { ru: "Цена", uk: "Ціна", be: "Цана", en: "Price" },
  colTime: { ru: "Время", uk: "Час", be: "Час", en: "Time" },
  colAction: { ru: "Действие", uk: "Дія", be: "Дзеянне", en: "Action" },
  cancel: { ru: "Отменить", uk: "Скасувати", be: "Адмяніць", en: "Cancel" },
  actionBuy: { ru: "Покупка", uk: "Купівля", be: "Купля", en: "Buy" },
  actionSell: { ru: "Продажа", uk: "Продаж", be: "Продаж", en: "Sell" },
  resetDemo: { ru: "Сбросить демо", uk: "Скинути демо", be: "Скінуць дэма", en: "Reset demo" },
  resetConfirm: {
    ru: "Сбросить баланс до $1 000 и удалить все позиции, заявки и историю?",
    uk: "Скинути баланс до $1 000 і видалити всі позиції, заявки та історію?",
    be: "Скінуць баланс да $1 000 і выдаліць усе пазіцыі, заяўкі і гісторыю?",
    en: "Reset your balance to $1,000 and clear all positions, orders and history?",
  },
  footer: {
    ru: "ZavtraMarket находится в разработке. Это демо: рынки, цены и объёмы вымышлены, торговля ведётся виртуальными деньгами.",
    uk: "ZavtraMarket перебуває в розробці. Це демо: ринки, ціни й обсяги вигадані, торгівля ведеться віртуальними грошима.",
    be: "ZavtraMarket знаходзіцца ў распрацоўцы. Гэта дэма: рынкі, цэны і аб'ёмы выдуманыя, гандаль вядзецца віртуальнымі грашыма.",
    en: "ZavtraMarket is in development. This is a demo: markets, prices and volumes are made up, and trading uses virtual money.",
  },
  joinWaitlist: { ru: "Записаться в лист ожидания", uk: "Записатися до списку очікування", be: "Запісацца ў спіс чакання", en: "Join the waitlist" },
};
